### ISSUE TITLE
Code Guidelines for different languges.

### ISSUE THREAD

**Issue by amanabt** [QuazarTech/Style-Guidelines#1]
**Commit Hash:** 726c811a43c75712304f8a927864507d7b5ca069 

## Short description of the Enhancement:
I propose that `code_guidelines` should be written in a separate folder separately for each of the
programming languages we will be using at Quazar.

## Why?
It is likely that we will be using languages other than `Python`. `C++` is already one of the
major language being used by @kchat79. So, I propose that `code_guidelines`
should be written in a separate folder separately for each of the programming languages we
will be using at Quazar.

## Possible implementation.
One of the possible implementations would be to store the code_guidelines for each language in a
`code_guidelines ` folder with the name of the file being the name of the language itself.
For eg. if the language is `python`, the code guidelines for writing code guidelines should be stored in:
`code_guidelines/python.md`

**Comment by amanabt** [comment]
Fixed the issue in the PR #2

**Comment by mchandra** [comment]
That is fine by me.

**Comment by amanabt** [comment]
issue resolved in PR #2
